version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: America/Sao_Paulo
  pull-request-branch-name:
    separator: "-"
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.8.1
    - 1.9.0
    - 1.9.1
  - dependency-name: omniauth
    versions:
    - 2.0.1
    - 2.0.2
    - 2.0.3
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
  - dependency-name: nokogiri
    versions:
    - 1.11.1
  - dependency-name: rake
    versions:
    - 13.0.3
  - dependency-name: omniauth-google-oauth2
    versions:
    - 0.8.1
  rebase-strategy: disabled
