version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: gem install bundler && bundle update --bundler
          command: bundle check || bundle install
      - run:
          name: Rubocop
          command: bundle exec rubocop
